<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CRMUNI.Domain\CRMUNI.Domain.csproj" />
      <ProjectReference Include="..\CRMUNI.Infra.Data\CRMUNI.Infra.Data.csproj" />
      <ProjectReference Include="..\CRMUNI.UnitTests.Domain\CRMUNI.UnitTests.Domain.csproj" />
    </ItemGroup>

</Project>
