// <auto-generated />
using System;
using CRMUNI.Infra.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRMUNI.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008150619_FuncionariosSetoresTabela")]
    partial class FuncionariosSetoresTabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRMUNI.DOMAIN.Entidades.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dthr_alteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dthr_criacao");

                    b.HasKey("Id");

                    b.ToTable("tb_empresas", (string)null);
                });

            modelBuilder.Entity("CRMUNI.DOMAIN.Entidades.Funcionarios.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dthr_alteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dthr_criacao");

                    b.Property<Guid?>("SetorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("id_setor")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.HasIndex("id_setor");

                    b.ToTable("tb_funcionarios", (string)null);
                });

            modelBuilder.Entity("CRMUNI.DOMAIN.Entidades.Setores.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dthr_alteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dthr_criacao");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasComment("Setores: 0-Comercial | 1-Financeiro | 2-Suporte");

                    b.Property<Guid>("id_empresa")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("id_empresa");

                    b.ToTable("tb_setores", (string)null);
                });

            modelBuilder.Entity("CRMUNI.DOMAIN.Entidades.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dthr_alteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dthr_criacao");

                    b.Property<Guid>("id_empresa")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("id_empresa");

                    b.ToTable("tb_usuarios", (string)null);
                });

            modelBuilder.Entity("CRMUNI.DOMAIN.Entidades.Empresas.Empresa", b =>
                {
                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.Geral.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("email");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("tb_empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.Documentos.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("nvarchar(14)")
                                .HasColumnName("cnpj");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("tb_empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.Nomes.NomeEmpresa", "Nome", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("nome");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("tb_empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.Telefones.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("telefone");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("tb_empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("CRMUNI.DOMAIN.Entidades.Funcionarios.Funcionario", b =>
                {
                    b.HasOne("CRMUNI.DOMAIN.Entidades.Setores.Setor", null)
                        .WithMany("Funcionarios")
                        .HasForeignKey("SetorId");

                    b.HasOne("CRMUNI.DOMAIN.Entidades.Setores.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("id_setor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.Geral.Email", "Email", b1 =>
                        {
                            b1.Property<int>("FuncionarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("email");

                            b1.HasKey("FuncionarioId");

                            b1.ToTable("tb_funcionarios");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioId");
                        });

                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.Funcionarios.Senha", "Senha", b1 =>
                        {
                            b1.Property<int>("FuncionarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("hash");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("salt");

                            b1.HasKey("FuncionarioId");

                            b1.ToTable("tb_funcionarios");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioId");
                        });

                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.Nomes.NomeFuncionario", "Nome", b1 =>
                        {
                            b1.Property<int>("FuncionarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("primeiro_nome");

                            b1.Property<string>("Segundo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("segundo_nome");

                            b1.HasKey("FuncionarioId");

                            b1.ToTable("tb_funcionarios");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("CRMUNI.DOMAIN.Entidades.Setores.Setor", b =>
                {
                    b.HasOne("CRMUNI.DOMAIN.Entidades.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("id_empresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.Nomes.NomeSetor", "Nome", b1 =>
                        {
                            b1.Property<Guid>("SetorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("nome");

                            b1.HasKey("SetorId");

                            b1.ToTable("tb_setores");

                            b1.WithOwner()
                                .HasForeignKey("SetorId");
                        });

                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.descricoes.DescricaoSetor", "DescricaoSetor", b1 =>
                        {
                            b1.Property<Guid>("SetorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("descricao");

                            b1.HasKey("SetorId");

                            b1.ToTable("tb_setores");

                            b1.WithOwner()
                                .HasForeignKey("SetorId");
                        });

                    b.Navigation("DescricaoSetor")
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Nome")
                        .IsRequired();
                });

            modelBuilder.Entity("CRMUNI.DOMAIN.Entidades.Usuarios.Usuario", b =>
                {
                    b.HasOne("CRMUNI.DOMAIN.Entidades.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("id_empresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.Geral.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("email");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("tb_usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.Funcionarios.Senha", "Senha", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("hash");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("salt");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("tb_usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("CRMUNI.DOMAIN.ObjetosValor.Nomes.NomeUsuario", "Nome", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("primeiro_nome");

                            b1.Property<string>("Segundo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("segundo_nome");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("tb_usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();
                });

            modelBuilder.Entity("CRMUNI.DOMAIN.Entidades.Setores.Setor", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
