// <auto-generated />
using System;
using CRMUNI.Infra.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRMUNI.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009120919_ContatoTabela")]
    partial class ContatoTabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Atendimentos.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrAlteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrCriacao");

                    b.Property<int>("EtapaId")
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasComment("Situacao: 0-Aguardando | 1-EmAndamento | 2-Finalizado");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("tb_atendimentos", (string)null);
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Contatos.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrAlteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrCriacao");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Origem")
                        .HasColumnType("int")
                        .HasComment("Origem: 0-Instagram | 1-Facebook | 2-Twitter | 3-LinkedIn | 4-Google | 5-Youtube | 6-Outros");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasComment("Situacao: 0-Ativo | 1-Inativo | 2-Bloqueado");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("tb_contatos", (string)null);
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrAlteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrCriacao");

                    b.HasKey("Id");

                    b.ToTable("tb_empresas", (string)null);
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Etapas.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrAlteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrCriacao");

                    b.Property<int?>("FunilId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasComment("Etapas: 0-Inicial | 1-PrimeiroContato | 2-ApresentacaoPlanos | 3-AguardandoDecicao | 4-Conversao | 5-Concluido | 6-Feedback | 7-Perdido");

                    b.HasKey("Id");

                    b.HasIndex("FunilId");

                    b.ToTable("tb_etapas", (string)null);
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Funcionarios.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrAlteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrCriacao");

                    b.Property<Guid>("SetorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("tb_funcionarios", (string)null);
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Funis.Funil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrAlteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrCriacao");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasComment("Funis: 0-Curioso | 1-Potencial Cliente | 2-Vendido");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("tb_funils", (string)null);
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Setores.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrAlteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrCriacao");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasComment("Setores: 0-Comercial | 1-Financeiro | 2-Suporte");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("tb_setores", (string)null);
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DthrAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrAlteracao");

                    b.Property<DateTime>("DthrCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DthrCriacao");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("tb_usuarios", (string)null);
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Atendimentos.Atendimento", b =>
                {
                    b.HasOne("CRMUNI.Domain.Entidades.Etapas.Etapa", "Etapa")
                        .WithMany("Atendimentos")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRMUNI.Domain.Entidades.Funcionarios.Funcionario", "Funcionario")
                        .WithMany("Atendimentos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Atendimentos.Agendamento", "Agendamento", b1 =>
                        {
                            b1.Property<int>("AtendimentoId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Data")
                                .HasColumnType("datetime2")
                                .HasColumnName("Agendamento");

                            b1.HasKey("AtendimentoId");

                            b1.ToTable("tb_atendimentos");

                            b1.WithOwner()
                                .HasForeignKey("AtendimentoId");
                        });

                    b.Navigation("Agendamento");

                    b.Navigation("Etapa");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Contatos.Contato", b =>
                {
                    b.HasOne("CRMUNI.Domain.Entidades.Empresas.Empresa", null)
                        .WithMany("Contatos")
                        .HasForeignKey("EmpresaId");

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Geral.Email", "Email", b1 =>
                        {
                            b1.Property<int>("ContatoId")
                                .HasColumnType("int");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.HasKey("ContatoId");

                            b1.ToTable("tb_contatos");

                            b1.WithOwner()
                                .HasForeignKey("ContatoId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Nomes.NomeContato", "Nome", b1 =>
                        {
                            b1.Property<int>("ContatoId")
                                .HasColumnType("int");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PrimeiroNome");

                            b1.Property<string>("Segundo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("SegundoNome");

                            b1.HasKey("ContatoId");

                            b1.ToTable("tb_contatos");

                            b1.WithOwner()
                                .HasForeignKey("ContatoId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Telefones.Celular", "Celular", b1 =>
                        {
                            b1.Property<int>("ContatoId")
                                .HasColumnType("int");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("nvarchar(13)")
                                .HasColumnName("Telefone");

                            b1.HasKey("ContatoId");

                            b1.ToTable("tb_contatos");

                            b1.WithOwner()
                                .HasForeignKey("ContatoId");
                        });

                    b.Navigation("Celular")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Empresas.Empresa", b =>
                {
                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Geral.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("tb_empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Documentos.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("nvarchar(14)")
                                .HasColumnName("Cnpj");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("tb_empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Nomes.NomeEmpresa", "Nome", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Nome");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("tb_empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Telefones.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("Telefone");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("tb_empresas");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.Navigation("Cnpj")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Etapas.Etapa", b =>
                {
                    b.HasOne("CRMUNI.Domain.Entidades.Funis.Funil", null)
                        .WithMany("Etapas")
                        .HasForeignKey("FunilId");

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Etapas.Ordem", "Ordem", b1 =>
                        {
                            b1.Property<int>("EtapaId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(18)")
                                .HasColumnName("Ordem");

                            b1.HasKey("EtapaId");

                            b1.ToTable("tb_etapas");

                            b1.WithOwner()
                                .HasForeignKey("EtapaId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Nomes.NomeEtapa", "Nome", b1 =>
                        {
                            b1.Property<int>("EtapaId")
                                .HasColumnType("int");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)")
                                .HasColumnName("Nome");

                            b1.HasKey("EtapaId");

                            b1.ToTable("tb_etapas");

                            b1.WithOwner()
                                .HasForeignKey("EtapaId");
                        });

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Ordem")
                        .IsRequired();
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Funcionarios.Funcionario", b =>
                {
                    b.HasOne("CRMUNI.Domain.Entidades.Setores.Setor", "Setor")
                        .WithMany("Funcionarios")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Geral.Email", "Email", b1 =>
                        {
                            b1.Property<int>("FuncionarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.HasKey("FuncionarioId");

                            b1.ToTable("tb_funcionarios");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Funcionarios.Senha", "Senha", b1 =>
                        {
                            b1.Property<int>("FuncionarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Hash");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Salt");

                            b1.HasKey("FuncionarioId");

                            b1.ToTable("tb_funcionarios");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Nomes.NomeFuncionario", "Nome", b1 =>
                        {
                            b1.Property<int>("FuncionarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PrimeiroNome");

                            b1.Property<string>("Segundo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("SegundoNome");

                            b1.HasKey("FuncionarioId");

                            b1.ToTable("tb_funcionarios");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Funis.Funil", b =>
                {
                    b.HasOne("CRMUNI.Domain.Entidades.Empresas.Empresa", null)
                        .WithMany("Funils")
                        .HasForeignKey("EmpresaId");

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Descricoes.DescricaoFunil", "Descricao", b1 =>
                        {
                            b1.Property<int>("FunilId")
                                .HasColumnType("int");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Descricao");

                            b1.HasKey("FunilId");

                            b1.ToTable("tb_funils");

                            b1.WithOwner()
                                .HasForeignKey("FunilId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Nomes.NomeFunil", "Nome", b1 =>
                        {
                            b1.Property<int>("FunilId")
                                .HasColumnType("int");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)")
                                .HasColumnName("Nome");

                            b1.HasKey("FunilId");

                            b1.ToTable("tb_funils");

                            b1.WithOwner()
                                .HasForeignKey("FunilId");
                        });

                    b.Navigation("Descricao")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Setores.Setor", b =>
                {
                    b.HasOne("CRMUNI.Domain.Entidades.Empresas.Empresa", null)
                        .WithMany("Setores")
                        .HasForeignKey("EmpresaId");

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Nomes.NomeSetor", "Nome", b1 =>
                        {
                            b1.Property<Guid>("SetorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Nome");

                            b1.HasKey("SetorId");

                            b1.ToTable("tb_setores");

                            b1.WithOwner()
                                .HasForeignKey("SetorId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.descricoes.DescricaoSetor", "DescricaoSetor", b1 =>
                        {
                            b1.Property<Guid>("SetorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Texto")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Descricao");

                            b1.HasKey("SetorId");

                            b1.ToTable("tb_setores");

                            b1.WithOwner()
                                .HasForeignKey("SetorId");
                        });

                    b.Navigation("DescricaoSetor")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Usuarios.Usuario", b =>
                {
                    b.HasOne("CRMUNI.Domain.Entidades.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Geral.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("tb_usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Funcionarios.Senha", "Senha", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Hash");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Salt");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("tb_usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("CRMUNI.Domain.ObjetosValor.Nomes.NomeUsuario", "Nome", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Primeiro")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PrimeiroNome");

                            b1.Property<string>("Segundo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("SegundoNome");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("tb_usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Empresas.Empresa", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Funils");

                    b.Navigation("Setores");
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Etapas.Etapa", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Funcionarios.Funcionario", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Funis.Funil", b =>
                {
                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("CRMUNI.Domain.Entidades.Setores.Setor", b =>
                {
                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
