<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Contexto\" />
      <Folder Include="Repositorios\Atendimentos\" />
      <Folder Include="Repositorios\Base\" />
      <Folder Include="Repositorios\Contatos\" />
      <Folder Include="Repositorios\Empresas\" />
      <Folder Include="Repositorios\Etapas\" />
      <Folder Include="Repositorios\Funcionarios\" />
      <Folder Include="Repositorios\Funis\" />
      <Folder Include="Repositorios\Mensagens\" />
      <Folder Include="Repositorios\Setores\" />
      <Folder Include="Repositorios\Usuarios\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CRMUNI.DOMAIN\CRMUNI.DOMAIN.csproj" />
    </ItemGroup>

</Project>
